# Generated by Django 3.1.2 on 2021-01-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210121_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
