# Generated by Django 3.1.2 on 2021-01-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_userinfo_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('img', models.ImageField(upload_to='')),
                ('auther', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('edition', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
